<?php

namespace App\Domains\Ps\Templates\Response;

class EventsDataCountCollectionPSResponseTemplate
{
    public static array $remoteResponse = [
        'data' => [
            0 => [
                "id" => 5,
                "user_id" => 1386,
                "cover_id" => 1,
                "cover_path" => null,
                "case_id" => 2,
                "reason_id" => 46,
                "date" => "2019-01-30 21 => 00 => 00",
                "start" => null,
                "end" => null,
                "name" => "Closed",
                "text" => "Поможем разработчику достигать большего.",
                "target" => null,
                "author_name" => "Dmitry",
                "author_lastname" => "Kremezion",
                "author_img_path" => "http => //avt-15.foto.mail.ru/inbox/kremezion/_avatar?1420800616",
                "video" => null,
                "video_embed" => null,
                "video_cover" => "",
                "photo" => null,
                "is_publish" => "0",
                "authors_thanks" => "",
                "closed" => null,
                "removed" => null,
                "status" => "removed",
                "tag" => "",
                "date_update" => "2021-07-22T10 => 51 => 45.000000Z",
                "isSum" => 1,
                "is_promo" => 0,
                "flags" => "[case]",
                "data" => "{\"reason\" => \"\",\"event_id\" => \"\",\"btn\" => \"\",\"logo\" => \"\",\"cover\" => \"\",\"margin_top_cover\" => \"\",\"auth_corp\" => \"false\"}",
                "is_master" => null,
                "url" => "",
                "language" => null,
                "logo" => null,
                "group_id" => 0,
                "view" => 59,
                "donations_count" => 0,
                "sum" => 49,
                "payments_thanks" => "",
                "created_at" => "2017-12-22T10 => 01 => 29.000000Z",
                "created_is" => null,
                "cache_url" => "Closed-2-1386",
                "id_master" => 0,
                "is_signup" => 1,
                "show_instruction" => 0,
                "meta_template" => null,
                "is_comment_photo" => 0,
                "is_code" => 0,
                "is_payments" => 0,
                "is_photo" => 0,
                "full_photo" => 0,
                "thanks_id" => null,
                "other_sum" => 0,
                "name_en" => null,
                "text_en" => null,
                "author_name_en" => null,
                "author_lastname_en" => null,
                "form_id" => null,
                "type" => 1
            ]
        ],
        'count' => 1
    ];

    public static array $outgoingResponse = [
        'data' => [
            0 => [
                "id" => 5,
                "user_id" => 1386,
                "cover_id" => 1,
                "cover_path" => null,
                "case_id" => 2,
                "reason_id" => 46,
                "date" => "2019-01-30 21 => 00 => 00",
                "start" => null,
                "end" => null,
                "name" => "Closed",
                "text" => "Поможем разработчику достигать большего.",
                "target" => null,
                "author_name" => "Dmitry",
                "author_lastname" => "Kremezion",
                "author_img_path" => "http => //avt-15.foto.mail.ru/inbox/kremezion/_avatar?1420800616",
                "video" => null,
                "video_embed" => null,
                "video_cover" => "",
                "photo" => null,
                "is_publish" => false,
                "authors_thanks" => "",
                "closed" => null,
                "removed" => null,
                "status" => "removed",
                "tag" => "",
                "date_update" => "2021-07-22T10 => 51 => 45.000000Z",
                "isSum" => true,
                "is_promo" => false,
                "flags" => "[case]",
                "data" => "{\"reason\" => \"\",\"event_id\" => \"\",\"btn\" => \"\",\"logo\" => \"\",\"cover\" => \"\",\"margin_top_cover\" => \"\",\"auth_corp\" => \"false\"}",
                "is_master" => null,
                "url" => "",
                "language" => null,
                "logo" => null,
                "group_id" => 0,
                "view" => 59,
                "donations_count" => 0,
                "sum" => 49,
                "payments_thanks" => "",
                "created_at" => "2017-12-22T10 => 01 => 29.000000Z",
                "created_is" => null,
                "cache_url" => "Closed-2-1386",
                "id_master" => false,
                "is_signup" => true,
                "show_instruction" => 0,
                "meta_template" => null,
                "is_comment_photo" => false,
                "is_code" => false,
                "is_payments" => false,
                "is_photo" => false,
                "full_photo" => 0,
                "thanks_id" => null,
                "other_sum" => 0,
                "name_en" => null,
                "text_en" => null,
                "author_name_en" => null,
                "author_lastname_en" => null,
                "form_id" => null,
                "type" => 1
            ]
        ],
        'count' => 1
    ];

    public static array $structureResponse = [
        'data' => [
            [
                "id",
                "user_id",
                "cover_id",
                "cover_path",
                "case_id",
                "reason_id",
                "date",
                "start",
                "end",
                "name",
                "text",
                "target",
                "author_name",
                "author_lastname",
                "author_img_path",
                "video",
                "video_embed",
                "video_cover",
                "photo",
                "is_publish",
                "authors_thanks",
                "closed",
                "removed",
                "status",
                "tag",
                "date_update",
                "isSum",
                "is_promo",
                "flags",
                "data",
                "is_master",
                "url",
                "language",
                "logo",
                "group_id",
                "view",
                "donations_count",
                "sum",
                "payments_thanks",
                "created_at",
                "created_is",
                "cache_url",
                "id_master",
                "is_signup",
                "show_instruction",
                "meta_template",
                "is_comment_photo",
                "is_code",
                "is_payments",
                "is_photo",
                "full_photo",
                "thanks_id",
                "other_sum",
                "name_en",
                "text_en",
                "author_name_en",
                "author_lastname_en",
                "form_id",
                "type"
            ],
        ],
        "count"
    ];
}
